### ISSUE TITLE
[Next Branch] Yae Doesn't Show Up in Basic Character Search

### ISSUE THREAD

**Issue by Tsym-or-Tysm** [genshinsim/gcsim.app#4]
From Kurt:
https://discord.com/channels/845087716541595668/869210750596554772/943637052581355590

![image](https://user-images.githubusercontent.com/84653157/154379574-631cd5ff-4be9-4eeb-90d4-82ba8a3a54c3.png)

**Comment by HanSeoulOh** [comment]
done with latest commit
